language: generic

sudo: requried

services:
  - docker

before_install:
  - docker build -t jnlee1102/docker-fullstack-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jnlee1102/docker-fullstack-app npm run test

after_success:
  - docker build -t jnlee1102/docker-frontend ./frontend
  - docker build -t jnlee1102/docker-backend ./backend
  - docker build -t jnlee1102/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push jnlee1102/docker-frontend
  - docker push jnlee1102/docker-backend
  - docker push jnlee1102/docker-nginx